server:
  port: 8081

spring:
  application:
    name: logicea-cards-project
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:logiceaCardsAPIDB}
    username: ${DB_USER:postgres}
  jpa:
    hibernate:
      ddl-auto: none

security:
  jwt:
    secretKey: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 720000000
